var bingoList = [];

bingoList[ 1 ] = [ {
	name: "Kill a boss swordless",
	name: "DRC Tingle Statue",
	name: "FW Tingle Statue",
	name: "DRC Compass",
	name: "FW Compass",
	name: "Map and Compass in Forsaken Fortress",
	name: "2 Dungeon Maps",
	name: "Any Horseshoe Island Sea Chart",
	name: "Survive a zombie hover",
	name: "Open 5 small chests",
	name: "Elixer Soup",
	name: "DRC Big Key",
	name: "HP from cannon shooting minigame",
	name: "Loot 3 submarines",
	name: "Swim into Jabun's Cavern",
	name: "Blue potion",
	name: "Endless night",
	name: "All FF2 searchlights facing upwards",
	name: "Get into Mother & Child island",
	name: "Open 10 small chests",
	name: "Windfall hide and seek",
	name: "Learn 2 Songs",
	name: "Swift sail",
	name: "Hero's Sword",
	name: "Bait Bag",
	name: "Spoils Bag",
	name: "Sail",
	name: "Pictobox",
	name: "Deluxe Pictobox",
	name: "Win an Auction",
	name: "1 of each spoil",
	name: "2 ledge clips",
	name: "200 Rupees",
	name: "Kill Kalle Demos with forest water",
	name: "Submarine bottle",
	name: "Change the savewarp flag away from Outset",
	name: "Telescope",
	name: "Beat FF1",
	name: "Biggest Quiver",
	name: "Biggest Bomb Bag",
	name: "1k Wallet",
	name: "Flight Control Platform HP",
	name: "Both Sploosh Kaboom Sea Charts",
	name: "Bird's Peak Rock Triforce Chart",
	name: "Isle of Steel Triforce Chart",
	name: "5 Sea Charts",
	name: "Place a pearl",
	name: "Master Sword",
	name: "Bottled forest firefly",
	name: "Open the Nintendo Gallery",
	name: "Bomb Isle HP",
	name: "Stone Watcher Platform HP",
	name: "Angular Isle HP",
	name: "Decorate Private Oasis"
}, ]